# Generated by Django 6.0.1 on 2026-01-19 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_phone', models.CharField(blank=True, max_length=30)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('national_id', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='rooms.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='tenants.student')),
            ],
            options={
                'indexes': [models.Index(fields=['active'], name='tenants_occ_active_2bd67f_idx'), models.Index(fields=['room', 'active'], name='tenants_occ_room_id_7e62ee_idx')],
            },
        ),
    ]
