# Generated by Django 6.0.1 on 2026-01-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Student full name', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Student phone number', max_length=20)),
                ('guardian_name', models.CharField(blank=True, help_text='Guardian full name', max_length=200)),
                ('guardian_phone', models.CharField(blank=True, help_text='Guardian phone number', max_length=20)),
                ('school', models.CharField(blank=True, help_text='School or University', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
